In [1]:
import numpy as np
from keras.utils import np_utils
import tensorflow as tf
#
# Initial Setup for Keras
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Flatten

# Using TensorFlow 1.0.0; use tf.python_io in later versions
# tf.python.control_flow_ops = tf

Using TensorFlow backend.


In [2]:
# Set random seed
np.random.seed(42)

In [3]:
# Our data
X = np.array([[0,0],[0,1],[1,0],[1,1]]).astype('float32')
y = np.array([[0],[1],[1],[0]]).astype('float32')

In [4]:
print("X = ")
print(X)
print("-------------------------")
print("y = ")
print(y)

X = 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
-------------------------
y = 
[[0.]
 [1.]
 [1.]
 [0.]]


In [5]:
# One-hot encoding the output
y = np_utils.to_categorical(y)

In [6]:
print("-------------------------")
print("y = ")
print(y)

-------------------------
y = 
[[1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]]


In [7]:
# Building the model
xor = Sequential()

In [8]:
# Add required layers
# xor.add( Dense(32, input_dim=2) )
xor.add( Dense(64, input_dim=2) )

xor.add( Activation("tanh") )
xor.add( Dense(2) )
xor.add( Activation("sigmoid") )
# xor.compile( loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"] )
xor.compile( loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"] )

In [9]:
# Specify loss as "binary_crossentropy", optimizer as "adam",
# and add the accuracy metric
# xor.compile()

In [10]:
# Uncomment this line to print the model architecture
xor.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                192       
_________________________________________________________________
activation_1 (Activation)    (None, 64)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 130       
_________________________________________________________________
activation_2 (Activation)    (None, 2)                 0         
Total params: 322
Trainable params: 322
Non-trainable params: 0
_________________________________________________________________


In [11]:
# Fitting the model
history = xor.fit(X, y, nb_epoch=1000, verbose=0)

C:\Users\mbd_p\Anaconda3\envs\UdaCity_01_Intro_ML\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


In [12]:
# Scoring the model
score = xor.evaluate(X, y)
print("\nAccuracy: ", score[-1])

# Checking the predictions
print("\nPredictions:")
print(xor.predict_proba(X))

4/4 [==============================] - 0s 8ms/step

Accuracy:  1.0

Predictions:
[[0.9946063  0.00414966]
 [0.00560763 0.9956951 ]
 [0.00572397 0.9950913 ]
 [0.99455774 0.00451396]]


In [13]:
xor.weights

[<tf.Variable 'dense_1/kernel:0' shape=(2, 64) dtype=float32_ref>,
 <tf.Variable 'dense_1/bias:0' shape=(64,) dtype=float32_ref>,
 <tf.Variable 'dense_2/kernel:0' shape=(64, 2) dtype=float32_ref>,
 <tf.Variable 'dense_2/bias:0' shape=(2,) dtype=float32_ref>]

In [14]:
X.shape

(4, 2)

In [15]:
y.shape

(4, 2)